// ignore_for_file: public_member_api_docs, sort_constructors_first
// ignore_for_file: non_constant_identifier_names

import 'dart:convert';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddJobRequestModel {
  int? JobId;
  int? UserId;
  int? CompanyId;
  int? JobStatusId;
  int? PurposeOfVisitId;
  int? ReasonId;
  String? ContactName;
  String? ContactMobileNo;
  String? JobLocation;
  double? Lat;
  double? Lon;
  String? StartDate;
  String? EndDate;
  String? StartTime;
  String? EndTime;
  String? CompletedEndTime;
  int? InsertMode;

  AddJobRequestModel({
    this.JobId,
    this.UserId,
    this.CompanyId,
    this.JobStatusId,
    this.PurposeOfVisitId,
    this.ReasonId,
    this.ContactName,
    this.ContactMobileNo,
    this.JobLocation,
    this.Lat,
    this.Lon,
    this.StartDate,
    this.EndDate,
    this.StartTime,
    this.EndTime,
    this.CompletedEndTime,
    this.InsertMode,
  });

  AddJobRequestModel.fromJson(Map<String, dynamic> json) {
    JobId = json['JobId']?.toInt();
    UserId = json['UserId']?.toInt();
    CompanyId = json['CompanyId']?.toInt();
    JobStatusId = json['JobStatusId']?.toInt();
    PurposeOfVisitId = json['PurposeOfVisitId']?.toInt();
    ReasonId = json['ReasonId']?.toInt();
    ContactName = json['ContactName']?.toString();
    ContactMobileNo = json['ContactMobileNo']?.toString();
    JobLocation = json['JobLocation']?.toString();
    Lat = json['Lat']?.toDouble();
    Lon = json['Lon']?.toDouble();
    StartDate = json['StartDate']?.toString();
    EndDate = json['EndDate']?.toString();
    StartTime = json['StartTime']?.toString();
    EndTime = json['EndTime']?.toString();
    CompletedEndTime = json['CompletedEndTime']?.toString();
    InsertMode = json['InsertMode']?.toInt();
  }

  Map<String, dynamic> toMap() {
    final data = <String, dynamic>{};
    data['JobId'] = JobId;
    data['UserId'] = UserId;
    data['CompanyId'] = CompanyId;
    data['JobStatusId'] = JobStatusId;
    data['PurposeOfVisitId'] = PurposeOfVisitId;
    data['ReasonId'] = ReasonId;
    data['ContactName'] = ContactName;
    data['ContactMobileNo'] = ContactMobileNo;
    data['JobLocation'] = JobLocation;
    data['Lat'] = Lat;
    data['Lon'] = Lon;
    data['StartDate'] = StartDate;
    data['EndDate'] = EndDate;
    data['StartTime'] = StartTime;
    data['EndTime'] = EndTime;
    data['CompletedEndTime'] = CompletedEndTime;
    data['InsertMode'] = InsertMode;
    return data;
  }

  String toJson() => json.encode(toMap());

  AddJobRequestModel copyWith({
    int? JobId,
    int? UserId,
    int? CompanyId,
    int? JobStatusId,
    int? PurposeOfVisitId,
    int? ReasonId,
    String? ContactName,
    String? ContactMobileNo,
    String? JobLocation,
    double? Lat,
    double? Lon,
    String? StartDate,
    String? EndDate,
    String? StartTime,
    String? EndTime,
    String? CompletedEndTime,
    int? InsertMode,
  }) {
    return AddJobRequestModel(
      JobId: JobId ?? this.JobId,
      UserId: UserId ?? this.UserId,
      CompanyId: CompanyId ?? this.CompanyId,
      JobStatusId: JobStatusId ?? this.JobStatusId,
      PurposeOfVisitId: PurposeOfVisitId ?? this.PurposeOfVisitId,
      ReasonId: ReasonId ?? this.ReasonId,
      ContactName: ContactName ?? this.ContactName,
      ContactMobileNo: ContactMobileNo ?? this.ContactMobileNo,
      JobLocation: JobLocation ?? this.JobLocation,
      Lat: Lat ?? this.Lat,
      Lon: Lon ?? this.Lon,
      StartDate: StartDate ?? this.StartDate,
      EndDate: EndDate ?? this.EndDate,
      StartTime: StartTime ?? this.StartTime,
      EndTime: EndTime ?? this.EndTime,
      CompletedEndTime: CompletedEndTime ?? this.CompletedEndTime,
      InsertMode: InsertMode ?? this.InsertMode,
    );
  }
}
